spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=${DB_DDL_AUTO:validate}
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.generate_statistics=false

application.security.jwt.secret-key=${JWT_SECRET_KEY}
application.security.jwt.expiration=86400000
application.security.jwt.refresh-token.expiration=604800000

henrik.api.key=${HENRIK_API_KEY}

application.cors.allowed-origins=${FRONTEND_URL}

spring.rabbitmq.host=${RABBITMQ_HOST}
spring.rabbitmq.port=${RABBITMQ_PORT:5672}
spring.rabbitmq.username=${RABBITMQ_USERNAME}
spring.rabbitmq.password=${RABBITMQ_PASSWORD}

spring.rabbitmq.relay.host=${RABBITMQ_HOST}
spring.rabbitmq.relay.port=${RABBITMQ_STOMP_PORT:61613}